export function generateInstallScript(config, selectedPlugins) {
  const { client, forkUrl, shell, useGit, dependencyInstaller, installPath, discordBranch, installOpenAsar } = config;

  // Helper to join lines
  const join = (lines) => lines.filter((l) => l !== null).join('\n');

  // PLUGIN SETUP HELPERS
  const getUserPluginBlock = (plugin, isEquicord) => {
    const targetDir = isEquicord ? 'Equicord\\src\\userplugins' : 'Vencord\\src\\userplugins';
    const repoUrl = plugin.clone_url;
    const pluginName = plugin.name;
    const branch = plugin.branch || plugin.default_branch;

    // PowerShell
    if (shell === 'powershell7' || shell === 'powershell5') {
      if (useGit) {
        return `Write-Host "Installing ${pluginName} (branch: ${branch})..."
git clone ${repoUrl} -b "${branch}" "${targetDir}\\${pluginName}"`;
      }
      return `Write-Host "Installing ${pluginName} (branch: ${branch})..."
$zipUrl = "${repoUrl}/archive/refs/heads/${branch}.zip"
$destZip = "${pluginName}.zip"
Invoke-WebRequest -Uri $zipUrl -OutFile $destZip
Expand-Archive -Path $destZip -DestinationPath "${targetDir}" -Force
Rename-Item -Path "${targetDir}\\${pluginName}-${branch}" -NewName "${pluginName}"
Remove-Item -Path $destZip`;
    }
    // Batch
    if (useGit) {
      return `echo Installing ${pluginName} (branch: ${branch})...
git clone ${repoUrl} -b "${branch}" "${targetDir}\\${pluginName}"`;
    }
    return `echo Installing ${pluginName} (branch: ${branch})...
powershell -Command "Invoke-WebRequest ${repoUrl}/archive/refs/heads/${branch}.zip -OutFile Plugin.zip"
powershell -Command "Expand-Archive -Path Plugin.zip -DestinationPath ."
move ${pluginName}-${branch} "${targetDir}\\${pluginName}"
del Plugin.zip`;
  };

  // --------------------------------------------------------------------------------
  // POWERSHELL GENERATOR
  // --------------------------------------------------------------------------------
  if (shell === 'powershell7' || shell === 'powershell5') {
    const isEquicord = client === 'Equicord';
    const clientName = isEquicord ? 'Equicord' : client === 'Vencord' ? 'Vencord' : 'Fork';
    const repo =
      client === 'Equicord'
        ? 'https://github.com/Equicord/Equicord'
        : client === 'Vencord'
          ? 'https://github.com/Vencord/Vencord'
          : forkUrl;

    const commands = [];

    commands.push(`# ${clientName} Installer Script generated by o9`);
    commands.push(`$ErrorActionPreference = "Stop"`);

    // Dependencies
    if (dependencyInstaller) {
      commands.push(`Write-Host "Checking/Installing Dependencies with ${dependencyInstaller}..."`);
      if (dependencyInstaller === 'winget') {
        if (useGit) commands.push(`winget install -e --id Git.Git`);
        commands.push(`winget install -e --id OpenJS.NodeJS`);
      } else if (dependencyInstaller === 'chocolatey') {
        if (useGit) commands.push(`choco install git -y`);
        commands.push(`choco install nodejs -y`);
      } else if (dependencyInstaller === 'scoop') {
        if (useGit) commands.push(`scoop install git`);
        commands.push(`scoop install nodejs`);
      }
      commands.push(`npm install -g pnpm`);
    }

    // Clone/Download Client
    commands.push(`Write-Host "Downloading ${clientName}..."`);
    if (installPath) commands.push(`cd "${installPath}"`);

    if (useGit) {
      commands.push(`git clone ${repo} ${clientName}`);
    } else {
      // Assuming main branch for client zip
      commands.push(`Invoke-WebRequest -Uri "${repo}/archive/refs/heads/main.zip" -OutFile "${clientName}.zip"`);
      commands.push(`Expand-Archive -Path "${clientName}.zip" -DestinationPath . -Force`);
      commands.push(`Rename-Item -Path "${clientName}-main" -NewName "${clientName}"`);
      commands.push(`Remove-Item -Path "${clientName}.zip"`);
    }

    // Plugins
    if (selectedPlugins.length > 0) {
      commands.push(`Write-Host "Setting up User Plugins..."`);
      commands.push(`New-Item -ItemType Directory -Force -Path "${clientName}\\src\\userplugins" | Out-Null`);
      selectedPlugins.forEach((p) => commands.push(getUserPluginBlock(p, isEquicord)));
    }

    // Build & Inject
    commands.push(`Write-Host "Building and Injecting..."`);
    commands.push(`cd "${clientName}"`);
    commands.push(`npm install -g pnpm`); // ensure pnpm
    commands.push(`pnpm install --frozen-lockfile`);
    commands.push(`pnpm build`);
    commands.push(`pnpm buildWeb`);
    const injectCmd = `pnpm inject${installOpenAsar ? ' -install-openasar' : ''}${discordBranch ? ` -branch ${discordBranch}` : ''}`;
    commands.push(injectCmd);

    return join(commands);
  }

  // --------------------------------------------------------------------------------
  // BATCH GENERATOR
  // --------------------------------------------------------------------------------
  if (shell === 'cmd') {
    const isEquicord = client === 'Equicord';
    const clientName = isEquicord ? 'Equicord' : client === 'Vencord' ? 'Vencord' : 'Fork';
    const repo =
      client === 'Equicord'
        ? 'https://github.com/Equicord/Equicord'
        : client === 'Vencord'
          ? 'https://github.com/Vencord/Vencord'
          : forkUrl;

    const commands = [];
    commands.push(`@echo off`);
    commands.push(`REM ${clientName} Installer Script`);

    // Dependencies
    if (dependencyInstaller) {
      commands.push(`REM Installing dependencies`);
      if (dependencyInstaller === 'winget') {
        if (useGit) commands.push(`winget install -e --id Git.Git`);
        commands.push(`winget install -e --id OpenJS.NodeJS`);
      }
      commands.push(`call npm install -g pnpm`);
    }

    // Clone/Download
    commands.push(`REM Downloading Client`);
    if (installPath) commands.push(`cd /d "${installPath}"`);

    if (useGit) {
      commands.push(`git clone ${repo} ${clientName}`);
    } else {
      commands.push(`powershell -Command "Invoke-WebRequest ${repo}/archive/refs/heads/main.zip -OutFile ${clientName}.zip"`);
      commands.push(`powershell -Command "Expand-Archive -Path ${clientName}.zip -DestinationPath ."`);
      commands.push(`ren ${clientName}-main ${clientName}`);
      commands.push(`del ${clientName}.zip`);
    }

    // Plugins
    if (selectedPlugins.length > 0) {
      commands.push(`REM Setup User Plugins`);
      commands.push(`mkdir "${clientName}\\src\\userplugins"`);
      selectedPlugins.forEach((p) => commands.push(getUserPluginBlock(p, isEquicord)));
    }

    // Build
    commands.push(`REM Build and Inject`);
    commands.push(`cd "${clientName}"`);
    commands.push(`call pnpm install --frozen-lockfile`);
    commands.push(`call pnpm build`);
    commands.push(`call pnpm buildWeb`);
    const injectCmd = `call pnpm inject${installOpenAsar ? ' -install-openasar' : ''}${discordBranch ? ` -branch ${discordBranch}` : ''}`;
    commands.push(injectCmd);

    return join(commands);
  }

  return 'Shell not supported yet.';
}
